### ISSUE TITLE
Tagged Template Literals

### ISSUE THREAD

**Issue by shellscape** [jorgebucaran/turbocolor#23]
Please consider adding support for tagged template literals. Without that feature, I'm afraid `turbocolor` can't truly be considered a drop-in replacement for `chalk`.

**Comment by jorgebucaran** [comment]
@shellscape You are right. Turbocolor is not an exact clone of chalk. It's still "close enough" to be considered a drop-in replacement IMO, but it lacks some of chalk features like the tagged function. 

The funny thing is we [had one](https://github.com/jorgebucaran/turbocolor/commit/40dc4e0a543c25ffc0ecfa6a19172e24e7baed7d) even before chalk [did](https://github.com/chalk/chalk/commit/f66271e01a901470a3d5afcb3feae552848ccf0c), but I later removed it because I didn't want to maintain a feature I am sure I'd never use. I still don't care so much about it.

Now, instead of making this built-in (again), I'd prefer if we came up with a factory function (as a separate module) that allow us to transform `turbocolor` (or any function with the same API like chalk) into a tagged function.

```js
exports.createTaggedFunction = c => (strings, ...values) =>
  strings
    .reduce((out, s, i) => out + (values[i - 1] || "") + s, "")
    .replace(/{([^{}]+)}/g, (_, block) =>
      block.replace(/([^ ]+) (.+)/g, (_, chain, value) =>
        chain.split(".").reduce((getter, i) => getter[i], c)(value)
      )
    )
```

Of course, it'll have to be something more robust than that if we want to handle nested blocks, escape curly braces and support blocks that split across multiple lines.

And use it like this.

```js
const t = require("./createTaggedFunction")(require("turbocolor"))

console.log(t`
  There are {yellow.bgBlack.bold.italic.inverse 5280 feet} in a mile.
  In {bold ${100} miles}, there are {red.bold ${(100 / 0.00018939) << 0}} feet.
`)
```
<img width="426" alt="screen shot 2018-08-11 at 19 24 37" src="https://user-images.githubusercontent.com/56996/43990842-35ef2de8-9d9c-11e8-9206-4b4d4fe361df.png">

---

**Comment by jorgebucaran** [comment]
I'm a little busy rewriting all my OSS tests for [testmatrix](https://github.com/jorgebucaran/testmatrix) and working on V2 release of Hyperapp, so I can't work on a new library at the moment, but maybe I'll pick it up later if nobody has beaten me to it.

Thanks! 👋
